apply from: 'gradle/scripts/helpers.gradle'

repositories {
    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com'
    }
    maven {
        name = 'CleanroomCurseMaven'
        url = 'https://curse.cleanroommc.com'
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
    mavenCentral()
    mavenLocal() // Must be last for caching to work
}

dependencies {
    compileOnly "com.cleanroommc:sponge-mixin:0.20.12+mixin.0.8.7"
    if (propertyBool('enable_lwjglx')) {
        compileOnly "com.cleanroommc:lwjglx:1.0.0"
    }

    modCompileOnly "curse.maven:jei-238222:5846804"
    modRuntimeOnly "curse.maven:jei-238222:5846804"
    modRuntimeOnly "curse.maven:forgelin-continuous-456403:7883992"
    modRuntimeOnly "curse.maven:spark-361579:3542217"
    modCompileOnly "curse.maven:patchouli-306770:3162874"
    modRuntimeOnly "curse.maven:patchouli-306770:3162874"
}
